language: go
go:
  - 1.7.x
  - 1.8.x
  - master
branches:
  only:
    - master
    - develop
install:
  - go get github.com/pkg/errors
  - go get github.com/pborman/uuid
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega
script: go test -v --cover ./...